### ISSUE TITLE
Make the text the correct size

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/slideshow#12]
Check the powerpoint files, and make the presentation match as closely as possible. (Probably needs MUCH larger font, like 3x larger.

``` css
/* maybe try this... */
.header { font-size: 40pt; }
body    { font-size: 60pt; }
```

Modify the preview reel as necessary to keep it looking like the presentation.
